# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    square:
      quality: 75
      filters:
        thumbnail:
          size: [450, 400]
          mode: outbound
    banniere:
      quality: 80
      filters:
        upscale:
          min: [1400, 1000]
        thumbnail:
          size: [1400, 1000]
          mode: outbound
    squareUne:
      quality: 75
      filters:
        thumbnail:
          size: [300, 300]
          mode: outbound
    banniereUne:
      quality: 80
      filters:
        upscale:
          min: [1400, 1000]
        thumbnail:
          size: [1400, 1000]
          mode: outbound
    avatar:
      quality: 80
      filters:
        upscale:
          min: [300, 300]
        thumbnail:
          size: [300, 300]
          mode: outbound
