vich_uploader:
  db_driver: orm

  mappings:
    profile_avatar:
      uri_prefix: /uploads/images/avatars
      upload_destination: "%kernel.project_dir%/public/uploads/images/avatar"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
    video_pics:
      uri_prefix: /uploads/videos/pics
      upload_destination: "%kernel.project_dir%/public/uploads/videos/pics"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
