twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
use Twig\Extra\Intl\IntlExtension;

$twig = new \Twig\Environment(...);
$twig->addExtension(new IntlExtension());